version: '3.4'

services:

  authentication:
    image: minifac_authentication
    build:
      context: ./minifac_authentication
      dockerfile: ./Dockerfile
    ports:
      - 5010:5010
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_authentication/authentication.py:/app/authentication.py
      - ${PWD}/minifac_authentication/templates:/app/templates
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  accounts:
    image: minifac_accounts
    build:
      context: ./minifac_accounts
      dockerfile: ./Dockerfile
    ports:
      - 5020:5020
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_accounts/accounts.py:/app/accounts.py
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  store:
    image: minifac_store
    build:
      context: ./minifac_store
      dockerfile: ./Dockerfile
    ports:
      - 5030:5030
    volumes:
      - ${PWD}/minifac_store/store.py:/app/store.py
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  customer:
    image: minifac_customer
    build:
      context: ./minifac_customer
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_customer/customer.py:/app/customer.py
      - ${PWD}/minifac_customer/templates:/app/templates
      - ${PWD}/minifac_customer/static:/app/static
    secrets:
      - accounts_auth

secrets:
  mysql_auth:
    file: mysql_auth.secret
  accounts_auth:
    file: accounts_auth.secret
