version: '3.4'

services:

  authentication:
    image: minifac_authentication
    build:
      context: ./minifac_authentication
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_authentication/authentication.py:/app/authentication.py
      - ${PWD}/minifac_authentication/templates:/app/templates
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  accounts:
    image: minifac_accounts
    build:
      context: ./minifac_accounts
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_accounts/accounts.py:/app/accounts.py
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  store:
    image: minifac_store
    build:
      context: ./minifac_store
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_store/store.py:/app/store.py
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  workloader:
    image: minifac_workloader
    build:
      context: ./minifac_workloader
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_workloader/workloader.py:/app/workloader.py
      - ${PWD}/minifac_workloader/process_endpoints.txt:/app/process_endpoints.txt
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
      MYSQL_DBNAME: minifac_db
    secrets:
      - mysql_auth
      - accounts_auth

  headassem:
    image: minifac_workprocpy
    build:
      context: ./minifac_workprocpy
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_workprocpy/workprocpy.py:/app/workprocpy.py
    environment:
      PROCESS_NAME: HeadAssy
      PROCESS_CONDS: '[["Create", "Success"], ["HeadAssy", "Rework"], [null, "Scrap"]]'
      PROCESS_TIME: 1.0
      PROCESS_YIELD: 60
      PROCESS_REWORK: 30
      PROCESS_SCRAP: 10

  bodyassem:
    image: minifac_workprocpy
    build:
      context: ./minifac_workprocpy
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/minifac_workprocpy/workprocpy.py:/app/workprocpy.py
    environment:
      PROCESS_NAME: BodyAssy
      PROCESS_CONDS: '[["HeadAssy", "Success"], ["BodyAssy", "Rework"]]'
      PROCESS_TIME: 1.0
      PROCESS_YIELD: 60
      PROCESS_REWORK: 30
      PROCESS_SCRAP: 10

  customer:
    image: minifac_customer
    build:
      context: ./minifac_customer
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ${PWD}/minifac_utils.py:/app/minifac_utils.py
      - ${PWD}/minifac_customer/customer.py:/app/customer.py
      - ${PWD}/minifac_customer/templates:/app/templates
      - ${PWD}/minifac_customer/static:/app/static
    secrets:
      - accounts_auth

secrets:
  mysql_auth:
    file: mysql_auth.secret
  accounts_auth:
    file: accounts_auth.secret
